proxy: fix compiler warnings on Debian Bullseye
[  191s] In file included from ../src/util/util.h:47,
[  191s]                  from ../src/providers/proxy/proxy.h:39,
[  191s]                  from ../src/providers/proxy/proxy_id.c:30:
[  191s] In function 'delete_user',
[  191s]     inlined from 'get_pw_uid' at ../src/providers/proxy/proxy_id.c:383:15,
[  191s]     inlined from 'proxy_account_info' at ../src/providers/proxy/proxy_id.c:1620:19,
[  191s]     inlined from 'proxy_account_info_handler_send' at ../src/providers/proxy/proxy_id.c:1763:20:
[  191s] ../src/util/debug.h:124:9: error: '%s' directive argument is null [-Werror=format-overflow=]
[  191s]   124 |         sss_debug_fn(__FILE__, __LINE__, __FUNCTION__, \
[  191s]       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  191s]   125 |                      __debug_macro_level, \
[  191s]       |                      ~~~~~~~~~~~~~~~~~~~~~~
[  191s]   126 |                      format, ##__VA_ARGS__); \
[  191s]       |                      ~~~~~~~~~~~~~~~~~~~~~~
[  191s] ../src/providers/proxy/proxy_id.c:215:5: note: in expansion of macro 'DEBUG'
[  191s]   215 |     DEBUG(SSSDBG_TRACE_FUNC,
[  191s]       |     ^~~~~
[  191s] ../src/providers/proxy/proxy_id.c: In function 'proxy_account_info_handler_send':
[  191s] ../src/providers/proxy/proxy_id.c:216:17: note: format string is defined here
[  191s]   216 |           "User %s does not exist (or is invalid) on remote server,"
[  191s]       |                 ^~

VRVDR-54735